name: CI
on: push
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        php: ["8.1", "8.2"]
        ts: ["ts", "nts"]
    steps:
      - name: Setup
        uses: shivammathur/setup-php@2.17.1
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          tools: phpcs, psalm, phpunit, infection
        env:
          fail-fast: true
          phpts: ${{ matrix.ts }}
          update: true

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - run: vendor/bin/phpcs --standard=psr12 src/
      - run: vendor/bin/psalm
      - run: vendor/bin/phpunit
      - run: vendor/bin/infection
